baseURL: https://dearalgorithm.github.io/joji_fx/
languageCode: en-us
defaultContentLanguage: en
title: joji_fx blog
theme: cupper-hugo-theme
googleAnalytics: UA-123456789-1
disqusShortname: yourdiscussshortname
enableGitInfo: true

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: An accessibility-friendly blog about Computer Science writted by Joji, built by Hugo and themed by Cupper.
  homeMetaContent: An accessibility-friendly Hugo theme, ported from the original Cupper project.
  footer: This blog runs under [MIT License](https://github.com/dearalgorithm/joji_fx/blob/main/LICENSE).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser
  katex: true
  hideHeaderLinks: false
  search: true
  showThemeSwitcher: true
  defaultDarkTheme: false
  moveFooterToHeader: false
  logoAlt: "Website logo: a square shape with unreadable code inside."
  customCss:
    - css/custom_01.css
    - css/custom_02.css
  customJs:
    - js/custom_01.js
    - js/custom_02.js

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: Hit me up!
      url: /contact/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
