baseURL = "https://dearalgorithm.github.io/joji_fx/"
languageCode = "en-us"
title = "joji_fx"
theme="archie"
copyright = "© Athul"
enableEmoji = true

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="auto" # color-mode → light,dark or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Having lots of fun documenting experiments related with Computer Science. I’ll be following the [RDFM and STFW](https://en.wikipedia.org/wiki/RTFM) standards as well as [The Tao of Programming](https://www.mit.edu/~xela/tao.html) guidelines. Please, don’t take the following lines too seriously 🐱‍💻"
	favicon                      = "./favicon/ship.svg"  

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/athulcajay/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
